rm /data_CMS/cms/motta/Run3preparation/Muon__Run2022FullRun3BtoG-PromptReco__MINIAOD__GoldenJSON__WMassCutTrue__ZMassCutTrue/Ntuple_113.root
rm /data_CMS/cms/motta/Run3preparation/Muon__Run2022FullRun3BtoG-PromptReco__MINIAOD__GoldenJSON__WMassCutTrue__ZMassCutTrue/Ntuple_13.root
rm /data_CMS/cms/motta/Run3preparation/Muon__Run2022FullRun3BtoG-PromptReco__MINIAOD__GoldenJSON__WMassCutTrue__ZMassCutTrue/Ntuple_14.root

rm /data_CMS/cms/motta/Run3preparation/Muon__Run2022FullRun3BtoG-PromptReco__MINIAOD__GoldenJSON__WMassCutTrue__ZMassCutTrue/log_113.txt
rm /data_CMS/cms/motta/Run3preparation/Muon__Run2022FullRun3BtoG-PromptReco__MINIAOD__GoldenJSON__WMassCutTrue__ZMassCutTrue/log_13.txt
rm /data_CMS/cms/motta/Run3preparation/Muon__Run2022FullRun3BtoG-PromptReco__MINIAOD__GoldenJSON__WMassCutTrue__ZMassCutTrue/log_14.txt

/home/llr/cms/motta/t3submit -long /data_CMS/cms/motta/Run3preparation/Muon__Run2022FullRun3BtoG-PromptReco__MINIAOD__GoldenJSON__WMassCutTrue__ZMassCutTrue/job_113.sh
/home/llr/cms/motta/t3submit -long /data_CMS/cms/motta/Run3preparation/Muon__Run2022FullRun3BtoG-PromptReco__MINIAOD__GoldenJSON__WMassCutTrue__ZMassCutTrue/job_13.sh
/home/llr/cms/motta/t3submit -long /data_CMS/cms/motta/Run3preparation/Muon__Run2022FullRun3BtoG-PromptReco__MINIAOD__GoldenJSON__WMassCutTrue__ZMassCutTrue/job_14.sh